name: OACrugs
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  image_pixels: ^3.0.2
  palette_generator: ^0.3.3
  flutter_launcher_icons: ^0.13.1
  image: ^4.2.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  fluttertoast: ^8.0.9




dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: assets/logos/app_icon.png

  flutter_lints: ^3.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/login/
    - assets/banner/
    - assets/guide/
    - assets/products/
    - assets/image/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
